services:
 app:
  container_name: golang-connect-line
  build:
   context: .
   dockerfile: ./build/Dockerfile.local
  volumes:
   - ./:/app/
  working_dir: /app
  env_file:
   - .env
  ports:
   - "${APP_PORT}:${APP_PORT}"
  networks:
   - golang-connect-line
 database:
  container_name: database-connect-line
  image: postgres:14.1-alpine
  shm_size: 1g
  restart: always
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=123456
  ports:
   - "5432:5432"
  volumes:
   - "./db/postgres/:/var/lib/postgresql/data"
  networks:
   - golang-connect-line
networks:
 golang-connect-line:
  name: golang-connect-line
  driver: bridge
